# Generated by Django 4.0.3 on 2022-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('expLevel', models.IntegerField()),
                ('trophies', models.IntegerField()),
                ('bestTrophies', models.IntegerField()),
            ],
        ),
    ]
